### ISSUE TITLE
As a registered user I want to be able to view the decks that I added to my profile and have the option to remove decks so that I can keep track of which decks I can play with

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#10]
# Acceptance Criteria
- The overview shows alls of the users decks
- The user can delete decks from the overview and is asked to confirm the deletion

# Tasks
- [x] sopra-fs22-group-10/client#27
- [x] sopra-fs22-group-10/client#28
- [x] sopra-fs22-group-10/server#60
- [x] sopra-fs22-group-10/server#61
- [x] sopra-fs22-group-10/server#62
