### ISSUE TITLE
As a registered user I want to add a card deck that another user has made to my user profile so that I can play with it when I start a game

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#11]
# Acceptance Criteria
- The deck overview has an option that allows users to link decks to their profile
- Linked decks can be selected when starting a game and are shown in the overview
- Public decks can be linked by any registered user and private decks require a code

# Tasks
- [ ] The deck overview has a button to add decks which opens an interface to select decks to be added
- [ ] When choosing to add a private deck, the user needs to enter a correct code
- [ ] The server can handle requests to add a deck
- [ ] The server can check whether a user is allowed to add a deck and respond appropriately
