### ISSUE TITLE
As a registered user, I want to be able to access my previously made card decks and edit them so that I can fix issues so that I can make them more enjoyable to play with. Editing them means adding or editing individual cards or changing the status of the card-set between public and private.

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#12]
# Acceptance Criteria
- The deck overview has an option to edit decks
- When choosing to edit a deck, the user enters a deck-editing screen which displays cards as well as an option for changing the name, picture and visibility
- The user can delete, add and edit individual cards
- Users can only edit their own decks

# Tasks
- [x] sopra-fs22-group-10/client#17
- [x] sopra-fs22-group-10/client#18
- [x] sopra-fs22-group-10/client#16
- [x] sopra-fs22-group-10/server#41
- [x] sopra-fs22-group-10/server#42
- [ ] sopra-fs22-group-10/client#29
