### ISSUE TITLE
As a registered user I want to be able to create card templates so that the creation of the cards is easier and all cards in a set have the same format and are comparable

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#13]
# Acceptance Criteria
- Only logged in users should be able to create and name the new template
- The user can choose the theme (e.g. cars, humans) for the card template (either custom or by selecting from a set of options)
- Choosing the comparison categories (e.g. horsepower, weight) up to a maximum of 5
- Choosing the comparison units and range of these units for the properties
- Choosing the representation style of the data from predefined styles
- The user has to define a number of units each cards must have
- When the user has chosen all his settings he can then save the template and use it afterwards to create cards

# Tasks
- [ ] There is a view for creating card templates, naming and saving them
- [ ] The template creation view lets user pick a theme, comparison categories and allowed values ranges and units
- [ ] The template creation view allows users to pick a visualization style
- [ ] The server can handle requests to create card templates
- [ ] The server can check whether a template creation request is valid and respond appropriately
- [ ] The server stores card templates and can make them available for card creation
