### ISSUE TITLE
As a registered and unregistered user I want to be able to create a card from a given template, so I can then play a game with those cards

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#14]
# Acceptance Criteria
- When creating the card, the template that needs to be respected is shown
- I can choose the name and the category values however I want (as long as it respects the template specification)
- After finishing the creation the user can save the card
- Saved cards are assigned to a deck

# Tasks
- [x] sopra-fs22-group-10/client#11
- [x] sopra-fs22-group-10/client#10
- [ ] sopra-fs22-group-10/client#12
- [x] sopra-fs22-group-10/server#29
- [x] sopra-fs22-group-10/server#30
- [x] sopra-fs22-group-10/server#31
