### ISSUE TITLE
As a user that is creating a card (registered or unregistered) I want to be able to add an image to my card (from the internet), so that the card is more fun to look at

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#15]
# Acceptance Criteria
- The user can obtain an image file with an image search API
- The user can add the image file to the card
- The image is visualized on the card and visible to other users

# Tasks
- [ ] The card creation features an interface that allows image search and selection
- [ ] Cards can be saved with an image
- [ ] A card can be visualized with its image
- [ ] The server can handle card creation requests for cards with images
- [ ] The database can store and return card objects such that they can be visualized with an image
