### ISSUE TITLE
As a registered user, I want to be able to log in to my account with my chosen credentials (username and password) to be able to use features reserved for registered users.

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#5]
# Acceptance Criteria
- Upon successful login, the site displays the user overview screen.
- Upon failure, an error message is displayed (“wrong username or password”)
- Logged in users can log out again

# Tasks
- [x] sopra-fs22-group-10/client#21
- [x] sopra-fs22-group-10/client#22
- [x] sopra-fs22-group-10/client#23
- [x] sopra-fs22-group-10/server#51
- [x] sopra-fs22-group-10/server#52
