### ISSUE TITLE
As a user that has created a deck I want to be able to have my deck evaluated for fairness (good point distribution), to make sure that the deck is fun to play with.

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#67]
# Acceptance Criteria
- The user has an option to check a deck for fairness
- The fairness check tells the user how cards need to be modified to make playing with a deck more enjoyable

# Tasks
- [ ] sopra-fs22-group-10/client#30
- [ ] sopra-fs22-group-10/server#64
- [ ] sopra-fs22-group-10/server#65
- [ ] sopra-fs22-group-10/server#66
- [ ] sopra-fs22-group-10/client#31
- [ ] sopra-fs22-group-10/client#32
- [ ] sopra-fs22-group-10/client#33
