### ISSUE TITLE
As a user that is editing a deck, I want to be able to pick a card and edit it, so that I can improve the deck.

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#71]
# Acceptance Criteria
- When editing a deck, the user can select individual cards to edit
- The user can change all properties of the card
- The changed properties are stored after editing

# Tasks
- [x] sopra-fs22-group-10/client#34
- [x] sopra-fs22-group-10/client#35
- [x] sopra-fs22-group-10/server#68
- [x] sopra-fs22-group-10/server#69
- [x] sopra-fs22-group-10/server#70
- [x] sopra-fs22-group-10/client#36
