### ISSUE TITLE
As a registered user I want to join a session from the main page by entering a unique game code

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#74]
# Acceptance Criteria
- By entering the correct code the user gets redirected to the corresponding session
- Only logged-in users can join a session
- When invalid code is entered, an notification shows up and tells the user to try again
- When valid code is entered, the user should be redirected to the corresponding session where they wait for the host to start the game

# Tasks
- [x] sopra-fs22-group-10/client#37
- [x] sopra-fs22-group-10/server#72
- [x] sopra-fs22-group-10/server#73
- [x] sopra-fs22-group-10/client#38
- [x] sopra-fs22-group-10/client#39
- [x] sopra-fs22-group-10/client#40
