### ISSUE TITLE
As a registered user I want to host a session.

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#77]
# Acceptance Criteria
- Only logged-in users can create a session
- With the creation of a session the host should receive a session code which he can share with other players so they can join his session.
- The session code should be unique so no two games have the same code
- The host should also be able to set all relevant options of the session. 
- Only one host should be allowed during one session. 

# Tasks
- [ ] sopra-fs22-group-10/client#41
- [x] sopra-fs22-group-10/client#42
- [x] sopra-fs22-group-10/client#43
- [x] sopra-fs22-group-10/server#75
- [x] sopra-fs22-group-10/server#76
- [x] sopra-fs22-group-10/client#44
