### ISSUE TITLE
As the host of a session I want to be able to select a deck from my library of decks which will then be the deck played in the game.

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#80]
# Acceptance Criteria
- The host should be able to select from a list with the default decks as well as the decks they own.
- After selecting a deck the host should be able to change their selection
- Only the host of the session is allowed to modify the selection of decks

# Tasks
- [ ] sopra-fs22-group-10/client#45
- [ ] sopra-fs22-group-10/client#46
- [ ] sopra-fs22-group-10/client#47
- [ ] sopra-fs22-group-10/server#78
- [ ] sopra-fs22-group-10/server#79
