### ISSUE TITLE
As the host of a session, I wait for players to join the session and start the game when people are ready. 

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#82]
# Acceptance Criteria
- The game can only be started when at least one deck is selected
- Every player should be able to leave the game before it starts
- The host can transfer the host identity to another player
- Only the host can start the game
- Once the host decides to start the game, all players are redirected to a game screen

# Tasks
- [ ] sopra-fs22-group-10/client#48
- [ ] sopra-fs22-group-10/client#49
- [ ] sopra-fs22-group-10/client#51
- [ ] sopra-fs22-group-10/client#52
- [ ] sopra-fs22-group-10/client#53
- [ ] sopra-fs22-group-10/server#81
