### ISSUE TITLE
As a player in my turn of the game, I want to select another player and a category to compare

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#84]
# Acceptance Criteria
- All players take turns to act
- In each turn, the player with the better card in the chosen category wins the top card from the other player
- A player with no cards cannot be selected anymore
- A player wins when he gets all cards
- Every player should be able to leave the game during the session

# Tasks
- [ ] sopra-fs22-group-10/client#54
- [ ] sopra-fs22-group-10/client#55
- [ ] sopra-fs22-group-10/client#56
- [ ] sopra-fs22-group-10/client#57
- [ ] sopra-fs22-group-10/client#58
- [ ] sopra-fs22-group-10/client#59
- [ ] sopra-fs22-group-10/client#60
- [ ] sopra-fs22-group-10/server#83
