### ISSUE TITLE
As the host of a session, I want to end a session

### ISSUE THREAD

**Issue by UlricaK** [sopra-fs22-group-10/server#86]
# Acceptance Criteria
- Only the host can end a session
- When the session ends, the players will be redirected to the main page
- When a game is finished, the host can request a new game, and each player is able to decline or accept the offer

# Tasks
- [ ] sopra-fs22-group-10/client#61
- [ ] sopra-fs22-group-10/client#62
- [ ] sopra-fs22-group-10/client#63
- [ ] sopra-fs22-group-10/client#64
- [ ] sopra-fs22-group-10/server#85
