### ISSUE TITLE
As a registered user I want to be able to create a new Deck in my “Deck overview” screen so that I can play with that deck in the future.

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/server#9]
# Acceptance Criteria
- The user can create a new deck by clicking on a button
- Once a deck is created the user has to be able to enter a name for the new deck
- Once a name is entered, the edit deck screen is automatically opened.

# Tasks
- [x] sopra-fs22-group-10/client#24
- [ ] sopra-fs22-group-10/client#25
- [ ] sopra-fs22-group-10/client#26
- [x] sopra-fs22-group-10/server#56
- [x] sopra-fs22-group-10/server#57
